
version: 2

models:
  - name: high_article_counts
    description: "dates where 5 or more articles were collected"
    columns:
      - name: date
        tests:
          - unique
          - not_null
      - name: article_count
        tests:
          - not_null

  - name: count_by_topic
    description: "article counts for each topic"
    columns:
      - name: topic_name
      - name: article_count

